no_trace: false
debounce: 300
ignore: \.git/
format:
  command_ok: "{{.Message}}\n"
  command_err: "\u001b[38;5;1m{{.Message}}\u001b[0m\n"
trig: [run]

rules:
- name: run-psql
  match: \.(go|env)$
  ignore: _test\.go$
  command: go run cmd/psql/main.go

- name: run-ent
  match: \.(go|env)$
  ignore: _test\.go$
  command: go run cmd/ent/main.go
